# Generated by Django 6.0.3 on 2026-04-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='judge_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
