# Generated by Codex on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_judge_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='extra_context',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='case',
            name='guest_alias',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='case',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='case',
            name='other_perspective',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='case',
            name='self_perspective',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='case',
            name='why_right',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='guest_alias',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
