# Generated by Codex on 2026-04-25

from datetime import timedelta

from django.db import migrations
from django.utils import timezone


def shorten_open_case_timers(apps, schema_editor):
    Case = apps.get_model('cases', 'Case')
    now = timezone.now()
    updated_unlock_time = now + timedelta(minutes=1)

    Case.objects.filter(
        status='open',
        verdict_timer_ends__isnull=False,
        verdict_timer_ends__gt=now,
    ).update(verdict_timer_ends=updated_unlock_time)


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_blueprint_flow_fields'),
    ]

    operations = [
        migrations.RunPython(shorten_open_case_timers, migrations.RunPython.noop),
    ]
