# Generated by Django 5.2.5 on 2026-04-06 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def cleanup_duplicate_votes(apps, schema_editor):
    Vote = apps.get_model('votes', 'Vote')
    # Keep the earliest vote found for each case-IP combination. 
    # Since all existing votes from Render will acquire the default '127.0.0.1', 
    # this step ensures we don't violate the uniqueness constraint.
    seen_keys = set()
    for vote in Vote.objects.all().order_by('id'):
        key = (vote.case_id, vote.ip_address)
        if key in seen_keys:
            vote.delete()
        else:
            seen_keys.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('votes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vote',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, default='127.0.0.1'),
            preserve_default=False,
        ),
        migrations.RunPython(cleanup_duplicate_votes),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('case', 'ip_address')},
        ),
    ]
