# Generated by Codex on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_alter_vote_unique_together_vote_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='decision',
            field=models.CharField(
                choices=[
                    ('you_messed_up', 'You Messed Up'),
                    ('they_messed_up', 'They Messed Up'),
                    ('both_messed_up', 'Both Messed Up'),
                    ('nobody_messed_up', 'Nobody Messed Up'),
                    ('guilty', 'Legacy: You Messed Up'),
                    ('not_guilty', 'Legacy: They Messed Up'),
                    ('esh', 'Legacy: Both Messed Up'),
                ],
                max_length=20,
            ),
        ),
    ]
